<%@ Page Title="Listes des cours" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Cours.aspx.cs" Inherits="MiniProjetDOTNET2020.WebForm1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <!DOCTYPE html>

    <html xmlns="http://www.w3.org/1999/xhtml">

    <body >
        <form id="form1" runat="server" style="margin-left : 20px" >
        
            <div style="margin-top : 20px" class="container">
                    <h2>Listes des cours</h2>
                <asp:GridView ID="CoursView" OnRowDeleting="GridView1_RowDeleting" runat="server" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" BorderStyle="Solid" CaptionAlign="Top" DataKeyNames="Id" AutoGenerateDeleteButton="True" >
                </asp:GridView>

            </div>
            <div class="container"  style="margin-top : 20px" >
                   <a href="CoursControllers/AjouterCours.aspx" style="text-decoration : none ; color : #fff">
                       <button type="button" class="btn btn-primary">
                          Ajouter
                       </button>
                   </a>
                <a href="CoursControllers/ModifierCours.aspx" style="text-decoration : none ; color : #fff">
                       <button type="button" class="btn btn-primary">
                           Modifier
                       </button>
                   </a>

            </div>
        
        </form>
    </body>
    </html>
</asp:Content>