<%@ Page Title="Listes de professeurs" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Professor.aspx.cs" Inherits="MiniProjetDOTNET2020.Professor" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <body>
        <form id="form1" runat="server">
            <div style="margin-top : 20px" class="container">
                <h2>Listes de professeurs</h2>
                <asp:GridView ID="GridView1" runat="server" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AutoGenerateDeleteButton="True" DataKeyNames="Id" OnRowDeleting="GridView1_RowDeleting">
                </asp:GridView>
            </div>
            <div class="container"  style="margin-top : 20px" >
               <a href="ProfControllers/AddProf.aspx" style="text-decoration : none ; color : #fff">
                       <button type="button" class="btn btn-primary">
                          Ajouter</button>
                   </a>
               <a href="ProfControllers/EditProf.aspx" style="text-decoration : none ; color : #fff">
                       <button type="button" class="btn btn-primary">
                          Modifier
                       </button>
               </a>
            </div>  
        </form>
    </body>
    

</asp:Content>
